<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

namespace Todo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>todo.Void</code>
 */
class PBVoid extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Todo::initOnce();
        parent::__construct();
    }

}

