<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

namespace GPBMetadata;

class Todo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a0a746f646f2e70726f746f1204746f646f22220a045461736b12" .
            "0c0a0474657874180120012809120c0a04646f6e6518022001280822250a" .
            "085461736b4c69737412190a057461736b7318012003280b320a2e746f64" .
            "6f2e5461736b22140a0454657874120c0a04746578741801200128092206" .
            "0a04566f6964324e0a055461736b7312240a044c697374120a2e746f646f" .
            "2e566f69641a0e2e746f646f2e5461736b4c6973742200121f0a03416464" .
            "120a2e746f646f2e546578741a0a2e746f646f2e5461736b220062067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

